site_name: Have fun! 
site_author: Sebastian Stolarski
site_url: https://github.com/essto/my-fAIve-minutes-app
site_description: >-
    essto/my-fAIve-minutes-app

repo_name: essto/my-fAIve-minutes-app
repo_url: https://github.com/essto/my-fAIve-minutes-app

theme:
  name: readthedos
  palette:
    primary: yellow
